development:
  adapter: postgresql
  encoding: unicode
  database: sinatra-todolist-development
  pool: 2
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: production